[package]
name = "file-server"
version = "1.0.0"
edition = "2018"
readme = "README.md"

[dependencies]
rocket = "0.5.0-rc.1"
rocket_dyn_templates = { version = "0.1.0-rc.1", features = ["tera"] }
serde = { version = "1.0", features = ["derive"] }
